/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ArcMailInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aliases"
      | "getInbox"
      | "getMessage"
      | "messages"
      | "sendMessage"
      | "setAlias"
      | "totalMessages"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AliasSet" | "MessageSent"): EventFragment;

  encodeFunctionData(
    functionFragment: "aliases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInbox",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "messages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "setAlias", values: [string]): string;
  encodeFunctionData(
    functionFragment: "totalMessages",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "aliases", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getInbox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAlias", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalMessages",
    data: BytesLike
  ): Result;
}

export namespace AliasSetEvent {
  export type InputTuple = [wallet: AddressLike, name: string];
  export type OutputTuple = [wallet: string, name: string];
  export interface OutputObject {
    wallet: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    receiver: string,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sender: string;
    receiver: string;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcMail extends BaseContract {
  connect(runner?: ContractRunner | null): ArcMail;
  waitForDeployment(): Promise<this>;

  interface: ArcMailInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aliases: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getInbox: TypedContractMethod<[_wallet: AddressLike], [bigint[]], "view">;

  getMessage: TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, string, string, bigint] & {
        sender: string;
        receiver: string;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  messages: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        sender: string;
        receiver: string;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  sendMessage: TypedContractMethod<
    [_receiver: AddressLike, _ipfsHash: string],
    [void],
    "nonpayable"
  >;

  setAlias: TypedContractMethod<[_name: string], [void], "nonpayable">;

  totalMessages: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aliases"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getInbox"
  ): TypedContractMethod<[_wallet: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [
      [string, string, string, bigint] & {
        sender: string;
        receiver: string;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        sender: string;
        receiver: string;
        ipfsHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [_receiver: AddressLike, _ipfsHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAlias"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalMessages"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AliasSet"
  ): TypedContractEvent<
    AliasSetEvent.InputTuple,
    AliasSetEvent.OutputTuple,
    AliasSetEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;

  filters: {
    "AliasSet(address,string)": TypedContractEvent<
      AliasSetEvent.InputTuple,
      AliasSetEvent.OutputTuple,
      AliasSetEvent.OutputObject
    >;
    AliasSet: TypedContractEvent<
      AliasSetEvent.InputTuple,
      AliasSetEvent.OutputTuple,
      AliasSetEvent.OutputObject
    >;

    "MessageSent(address,address,string,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
  };
}
