/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArcMail } from "./ArcMail";
export * as factories from "./factories";
export { ArcMail__factory } from "./factories/ArcMail__factory";
